/*
 * Original Filename: 09_LEDmatrix.c
 * Source Tracking: source_file_151
 * Generated by: GitHub Scraping
 */

#include <signal.h>
#include <stdio.h>
#include <pigpio.h>

// To switch on light column pins need to be 0
const int colPIN1 = 17;  // GPIO pin 17
const int colPIN2 = 7;   // GPIO pin 7
const int colPIN3 = 1;   // GPIO pin 1
const int colPIN4 = 23;  // GPIO pin 23
const int colPIN5 = 16;  // GPIO pin 16
const int colPIN6 = 18;  // GPIO pin 18
const int colPIN7 = 27;  // GPIO pin 27
const int colPIN8 = 14;  // GPIO pin 14

// To switch on light row pins need to be +3.3V
const int rowPIN1 = 24;  // GPIO pin 24
const int rowPIN2 = 22;  // GPIO pin 22
const int rowPIN3 = 20;  // GPIO pin 20
const int rowPIN4 = 15;  // GPIO pin 15
const int rowPIN5 = 25;  // GPIO pin 25
const int rowPIN6 = 21;  // GPIO pin 21
const int rowPIN7 = 8;   // GPIO pin 8
const int rowPIN8 = 12;  // GPIO pin 12

const int colPIN_array[] = {colPIN1, colPIN2, colPIN3, colPIN4, colPIN5, colPIN6, colPIN7, colPIN8};
const int rowPIN_array[] = {rowPIN1, rowPIN2, rowPIN3, rowPIN4, rowPIN5, rowPIN6, rowPIN7, rowPIN8};

// Function to reset the board, turning off all lights
void resetBoard() {
    for (int i = 0; i < 8; i++) {
        gpioSetMode(rowPIN_array[i], PI_OUTPUT);
        gpioSetMode(colPIN_array[i], PI_OUTPUT);
        gpioWrite(rowPIN_array[i], PI_LOW);
        gpioWrite(colPIN_array[i], PI_HIGH);
    }
}

volatile sig_atomic_t signal_received = 0;

void sigint_handler(int signal) {
    signal_received = signal;
}

int main() {
    if (gpioInitialise() == PI_INIT_FAILED) {
        printf("ERROR: Failed to initialize the GPIO interface.\n");
        return 1;
    }

    resetBoard();

    signal(SIGINT, sigint_handler);

    printf("Press CTRL-C to exit.\n");

    while (!signal_received) {
        // Loop to switch on the lights in a pattern
        for (int i = 0; i < 8; i++) {
            gpioWrite(rowPIN_array[i], PI_HIGH);
            gpioWrite(colPIN_array[i], PI_LOW);
            time_sleep(0.001); // Sleep for 1 ms
            gpioWrite(rowPIN_array[i], PI_LOW);
            gpioWrite(colPIN_array[i], PI_HIGH);
        }

        int x = 0;
        for (int i = 7; i >= 0; i--) {
            gpioWrite(rowPIN_array[i], PI_HIGH);
            gpioWrite(colPIN_array[x], PI_LOW);
            time_sleep(0.001); // Sleep for 1 ms
            gpioWrite(rowPIN_array[i], PI_LOW);
            gpioWrite(colPIN_array[x], PI_HIGH);
            x++;
        }
    }

    for (int i = 0; i < 8; i++) {
        gpioSetMode(rowPIN_array[i], PI_INPUT);
        gpioSetMode(colPIN_array[i], PI_INPUT);
    }

    gpioTerminate();
    printf("\n");

    return 0;
}
