/*
 * Original Filename: file_96.c
 * Source Tracking: source_file_138
 * Generated by: BCM GitHub Scraping
 */

/*
 * Original Filename: Active_Buzzer.c
 * Source Tracking: source_file_96
 * Generated by: BCM GitHub Scraping
 */

#include <wiringPi.h>
#include <stdio.h>
#define button 1   //button pin BCM GPIO 18
#define buzzer 2   //buzzer pin BCM GPIO 27
int main()
{
  wiringPiSetup();
  char val;
  {
    pinMode(button,INPUT);  //set the button pin INPUT mode
    pinMode(buzzer,OUTPUT);
  }
  
  while(1)
  {
    val=digitalRead(button);  // digital read
    printf("val = %d\n", val);
    if(val==0)//check if the button is pressed, if yes, turn on the Buzzer
      digitalWrite(buzzer,HIGH);  //The buzzer made a sound
    else
      digitalWrite(buzzer,LOW);
  }	
}
