/*
 * Original Filename: file_103.c
 * Source Tracking: source_file_133
 * Generated by: BCM GitHub Scraping
 */

/*
 * Original Filename: HelloWorld.c
 * Source Tracking: source_file_103
 * Generated by: BCM GitHub Scraping
 */

#include <wiringPi.h>   //wiringPi GPIO library
#include <stdio.h>  //standard input & output library

int main()  //Main function, the entry of the program
{
  
  wiringPiSetup();  //Initializes the wiringPi GPIO library
  while(1)  //An infinite loop
  {
    printf("Hello World!\n");  //\n is a newline print
    delay(1000);  //delay 1000ms
  }
}
