/*
 * Original Filename: file_102.c
 * Source Tracking: source_file_132
 * Generated by: BCM GitHub Scraping
 */

/*
 * Original Filename: Flame_Sensor.c
 * Source Tracking: source_file_102
 * Generated by: BCM GitHub Scraping
 */

#include <wiringPi.h>
#include <stdio.h>
#define flamePin 1  //BCM GPIO 18
#define buzPin 2  //define buzzer pin  BCM GPIO 27

int main()
{
  wiringPiSetup();
  char val;
  {
    pinMode(flamePin,INPUT);
    pinMode(buzPin,OUTPUT);
  }
  
  while(1)
  { 
   val=digitalRead(flamePin);
   printf("val = %d\n",val);
   if(val==1) //When flame is detected
    digitalWrite(buzPin,HIGH);  //Buzzer turn on
   else
    digitalWrite(buzPin,LOW);  //Buzzer turn off
  }	
}
