/*
 * Original Filename: first.c
 * Source Tracking: source_file_170
 * Generated by: GitHub Scraping
 */

#include <stdio.h>
int main() {
    printf("Content-Type: text/html\n\n");
    printf("Hello world");
    return 0;
}